[build]
builder = "NIXPACKS"

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python -m playwright install --with-deps chromium"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
